import glob
import os.path
import sys

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

# take driver name from directory name, replace if you don't like the result
driverName = os.path.basename( Dir( '.' ).srcnode().abspath )

# automatically glob files
headers = globSourceFiles( '*.h' )
sources = globSourceFiles( '*.cpp' )


uterrorvis_options = mergeOptions( boost_options, opencv_options, tinyxml_options, utcore_options, utvision_options, log4cpp_options, lapack_options, utfacade_options)
uterrorvis_options ['CPPPATH'] += [ getCurrentPath() ]

env.Append( CPPDEFINES = 'UTERRORVISUTIL_DLL' )


env.AppendUnique( **uterrorvis_options )



# compile driver
libs = setupLibraryBuild(env, sources, driverName)

uterrorvis_options[ 'LIBS' ] += libs
uterrorvis_options[ 'LIBPATH' ] += [ install_library_prefix ]

Export('uterrorvis_options')

createVisualStudioProject(env, sources, headers, driverName)