LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)


LOCAL_MODULE    := OpenGLTextureUpdate

LOCAL_SRC_FILES += OpenGLTextureUpdate.cpp

LOCAL_LDLIBS 	+=  -lGLESv2

#LOCAL_CPPFLAGS 	+= -DANDROID_DEBUG=1
#LOCAL_CFLAGS 	+= -DANDROID_DEBUG=1
#LOCAL_CPPFLAGS += -DANDROID22=1
#LOCAL_CFLAGS +=  -DANDROID22=1

include $(BUILD_SHARED_LIBRARY)