/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tum_far_imagerecorder_NDKImageRecorder */

#ifndef __CAMERA_TO_TEX_AND_TCP__
#define __CAMERA_TO_TEX_AND_TCP__
#ifdef __cplusplus
extern "C" {
#endif

	void updateSubTextureRGBA32(int textureID, int xOffset, int yOffset, int width, int height, void* buffer);
	void updateTextureRGBA32(int textureID, int width, int height, void* buffer);



#ifdef __cplusplus
}
#endif
#endif
