import os

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

# add the main file
sources = [ 'console.cpp' ]

# setup compiler and linker flags
config_options = mergeOptions( utfacade_all_options)
env.AppendUnique( **config_options )
env.AppendUnique( LIBS = boost_libs( [ 'program_options' ] ) )

# fix library search paths on gnu linker
if 'gnulink' in env[ 'TOOLS' ]:
	boost_rpath = map( lambda x: Dir( x ).abspath, boost_options[ 'LIBPATH' ] )
	env.Append( RPATH = boost_rpath + [ env.Literal( "'$$ORIGIN/../lib'" ) ] )

# build the console
setupAppBuild(env, sources, 'utConsole', 'facade')


# also create a visual studio project for the library	
createVisualStudioProject(env, sources, [], 'utFacade-Console')

