import glob

Import( '*' )

if not have_utfacade:
	print "utFacade missing -- not building facade apps"
	success = False
	Return('success')

# glob all SConscript files in subdirectories
sconsfiles = globSourceFiles( "*/SConscript" )

# recurse into subdirectories and export driver build environment
SConscript( sconsfiles )
success = True
Return('success')
