import glob

Import( '*' )

if not have_utdataflow:
	success = False
	have_utfacade = False
	Export('have_utfacade')
	Return('success')

sconsfiles = [ "utFacade/SConscript", "utComponents/SConscript" ]

# recurse into subdirectories and export driver build environment
SConscript( sconsfiles )
success = True
Return('success')
